// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cppMarkovTransitionsAndTrace
List cppMarkovTransitionsAndTrace(NumericMatrix transitions, DataFrame valuesTransitional, DataFrame valuesResidency, DataFrame modelStartValues, NumericVector initialProbs, CharacterVector stateNames, CharacterVector valueNames, int nCycles, double complementConstant, std::string halfCycleMethod);
RcppExport SEXP _openqaly_cppMarkovTransitionsAndTrace(SEXP transitionsSEXP, SEXP valuesTransitionalSEXP, SEXP valuesResidencySEXP, SEXP modelStartValuesSEXP, SEXP initialProbsSEXP, SEXP stateNamesSEXP, SEXP valueNamesSEXP, SEXP nCyclesSEXP, SEXP complementConstantSEXP, SEXP halfCycleMethodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type transitions(transitionsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type valuesTransitional(valuesTransitionalSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type valuesResidency(valuesResidencySEXP);
    Rcpp::traits::input_parameter< DataFrame >::type modelStartValues(modelStartValuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initialProbs(initialProbsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type stateNames(stateNamesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type valueNames(valueNamesSEXP);
    Rcpp::traits::input_parameter< int >::type nCycles(nCyclesSEXP);
    Rcpp::traits::input_parameter< double >::type complementConstant(complementConstantSEXP);
    Rcpp::traits::input_parameter< std::string >::type halfCycleMethod(halfCycleMethodSEXP);
    rcpp_result_gen = Rcpp::wrap(cppMarkovTransitionsAndTrace(transitions, valuesTransitional, valuesResidency, modelStartValues, initialProbs, stateNames, valueNames, nCycles, complementConstant, halfCycleMethod));
    return rcpp_result_gen;
END_RCPP
}
// cppCalculateTraceAndValues
List cppCalculateTraceAndValues(NumericVector init, NumericMatrix transitions, DataFrame values, CharacterVector value_names, CharacterVector state_names, DataFrame expanded_state_map, std::string half_cycle_method);
RcppExport SEXP _openqaly_cppCalculateTraceAndValues(SEXP initSEXP, SEXP transitionsSEXP, SEXP valuesSEXP, SEXP value_namesSEXP, SEXP state_namesSEXP, SEXP expanded_state_mapSEXP, SEXP half_cycle_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type transitions(transitionsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type value_names(value_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type state_names(state_namesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type expanded_state_map(expanded_state_mapSEXP);
    Rcpp::traits::input_parameter< std::string >::type half_cycle_method(half_cycle_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(cppCalculateTraceAndValues(init, transitions, values, value_names, state_names, expanded_state_map, half_cycle_method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_openqaly_cppMarkovTransitionsAndTrace", (DL_FUNC) &_openqaly_cppMarkovTransitionsAndTrace, 10},
    {"_openqaly_cppCalculateTraceAndValues", (DL_FUNC) &_openqaly_cppCalculateTraceAndValues, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_openqaly(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
