// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cppMarkovTransitionsAndTrace
List cppMarkovTransitionsAndTrace(DataFrame transitions, DataFrame valuesTransitional, NumericVector initialProbs, CharacterVector stateNames, CharacterVector valueNames, int nCycles, double complementConstant);
RcppExport SEXP _heRomod2_cppMarkovTransitionsAndTrace(SEXP transitionsSEXP, SEXP valuesTransitionalSEXP, SEXP initialProbsSEXP, SEXP stateNamesSEXP, SEXP valueNamesSEXP, SEXP nCyclesSEXP, SEXP complementConstantSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type transitions(transitionsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type valuesTransitional(valuesTransitionalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initialProbs(initialProbsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type stateNames(stateNamesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type valueNames(valueNamesSEXP);
    Rcpp::traits::input_parameter< int >::type nCycles(nCyclesSEXP);
    Rcpp::traits::input_parameter< double >::type complementConstant(complementConstantSEXP);
    rcpp_result_gen = Rcpp::wrap(cppMarkovTransitionsAndTrace(transitions, valuesTransitional, initialProbs, stateNames, valueNames, nCycles, complementConstant));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_heRomod2_cppMarkovTransitionsAndTrace", (DL_FUNC) &_heRomod2_cppMarkovTransitionsAndTrace, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_heRomod2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
